quarkus.http.port=8082
quarkus.http.test-port=0

quarkus.smallrye-openapi.info-title=Bookings API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Book tennis courts for players.
%prod.quarkus.smallrye-openapi.enabled=false

quarkus.rest-client.players-api.url=http://localhost:8080
quarkus.rest-client.courts-api.url=http://localhost:8081