quarkus.http.port=8080
quarkus.http.test-port=0
quarkus.smallrye-openapi.info-title=Players API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Manage tennis players.
%prod.quarkus.smallrye-openapi.enabled=false